dist: xenial

language: python
python:
 - "2.7"
 - "3.6"
 - "3.7"
 
addons:
  apt:
    update: true
 
before_install:
 - sudo add-apt-repository ppa:andreasgocht/scorep
 - sudo apt-get update -q
 - sudo apt-get install -y scorep

script:
  - pip install ./ && cd test $$ python test.py
