name: Publishing on PyPi
on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish Python 🐍 distributions 📦 to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - id: cache
      uses: actions/cache@v1
      with:
        path: ~/scorep
        key: scorep

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Check Version
      run: test ${{ github.event.release.tag_name }} = `python -c "import scorep._version; print('v'+scorep._version.__version__)"`
    - name: Install dependencies
      run: sudo add-apt-repository ppa:andreasgocht/scorep
      run: sudo apt install scorep
    - name: Setup environment
      run: echo "$HOME/scorep/bin" >> $GITHUB_PATH

    - name: Install pypa/build
      run: >-
        python -m
        pip install build --user
    - name: Build a source tarball
      run: >-
        python -m
        build --sdist --outdir dist/ .
    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
