name: Publishing on PyPi
on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish Python 🐍 distributions 📦 to TestPyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - id: cache
      uses: actions/cache@v1
      with:
        path: ~/scorep
        key: scorep

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Check Version
      run: test ${{ github.event.release.tag_name }} = python -c "import scorep._version; print(scorep._version.__version__)"
    - name: Install system dependencies
      run: sudo apt install gcc-7-plugin-dev libopenmpi-dev openmpi-bin
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        mkdir /tmp/buildScorep && cd /tmp/buildScorep
        wget https://www.vi-hps.org/cms/upload/packages/scorep/scorep-6.0.tar.gz
        tar xf scorep-6.0.tar.gz
        cd scorep-6.0
        mkdir build && cd build
        ../configure --enable-shared --prefix=$HOME/scorep
        make -j3 && make install
    - name: Setup environment
      run: echo "$HOME/scorep/bin" >> $GITHUB_PATH

    - name: Install pypa/build
      run: >-
        python -m
        pip install build --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build --sdist --outdir dist/ .
    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
