name: Unit tests
on: [push, pull_request]

env:
  SCOREP_TIMER: clock_gettime # tsc causes warnings

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [2.7, 3.5, 3.6, 3.7, 3.8]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip
    - id: cache
      uses: actions/cache@v1
      with:
        path: ~/scorep
        key: scorep

    - name: Install dependencies
      run: sudo add-apt-repository ppa:andreasgocht/scorep
      run: sudo apt install scorep

    - name: Setup environment
      run: echo "$HOME/scorep/bin" >> $GITHUB_PATH
    - name: set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python}}
        architecture: x64
    - name: Install Python packages
      run: |
        pip install --upgrade pip
        pip install numpy mpi4py pytest

    - name: Build python bindings
      run: pip install .
    - name: Run tests
      working-directory: test
      run: pytest